add: linters were fixed

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -29,5 +29,9 @@ fi
 
 echo "$init_icon Start linting"
 npm run lint-staged-files
+if [ $? -ne 0 ]; then
+    echo "$error_icon Lint errors were found"
+    exit 1
+fi
 
 echo "$ok_icon changes were commited"
