add: ci fixes

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -4,15 +4,15 @@ forbidden_branches='main'
 current_branch=$(git branch --show-current)
 
 for branch in $forbidden_branches; do
-    if [$branch == $current_branch]; then
-        echo "direct commits to main branch are forbidden"
+    if [ "$branch" = "$current_branch" ]; then
+        echo "Direct commits to main branch are forbidden"
         exit 1
-    if
+    fi
 done
 
 echo "TypeScript started"
 npm run type-check
-if [$? -ne 0]; then
-    echo "Type errors was founded"
+if [ $? -ne 0 ]; then
+    echo "Type errors were found"
     exit 1
-if
+fi
